typography_spectrum: 0.8680864563211799
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4508660731371492
  lightness: 0.09029609430581331
  saturation: 0.9852218441665173
  rhythmicContrast: 0.4374654476996511
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3762576808221638
analytics:
  google: null
  facebook: null
  twitter: null
name: lauracoates
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Going into the Wormhole
description: Understanding where you are and what you're becoming
purpose: []
